App\Entity\Book:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    title:
      type: string
      nullable: false
      unique: true
    release_date:
#      @TODO implement before death dates
      type: date
      nullable: true
    catalog_date:
      type: datetime
#      deprecated feature on doctrine level , see more here https://github.com/doctrine/doctrine2/issues/6346
      columnDefinition: TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL
      options:
        default: CURRENT_TIMESTAMP
    rate:
      type: float
      length: 10
#  https://symfony.com/doc/current/doctrine/lifecycle_callbacks.html
  lifecycleCallbacks:
    prePersist: [setCatalogDateValue]
  manyToOne:
#    https://symfony.com/doc/current/doctrine/associations.html
    genre:
      targetEntity: App\Entity\Genre
      joinColumn:
        nullable: false
    author:
      targetEntity: App\Entity\Author
      joinColumn:
        nullable: false