#index:
#    path: /
#    controller: App\Controller\DefaultController::index
register:
  path: /registeruser
  controller: App\Controller\UserRegistrationController::register

profile:
  path: /profile
  controller: App\Controller\UserController::profile

login:
  #delegate login to security controller https://symfony.com/doc/current/security/form_login_setup.html
  path: /login
  #controller: App\Controller\UserController::login
  controller: App\Controller\SecurityController::login

logout:
  path: /logout
  controller: App\Controller\UserController::logout

user_delete:
  path: /user/delete
  controller: App\Controller\UserController::delete

authors:
  path: /authors
  controller: App\Controller\AuthorController::index

#  @TODO add all other routes for CRUD operations under Author's entities, from annotations in  AuthorController
