#index:
#    path: /
#    controller: App\Controller\DefaultController::index
register:
  path: /registeruser
  controller: App\Controller\UserRegistrationController::register

profile:
  path: /profile
  controller: App\Controller\UserController::profile

login:
  path: /login
  controller: App\Controller\UserController::login

logout:
  path: /logout
  controller: App\Controller\UserController::logout

user_delete:
  path: /user/delete
  controller: App\Controller\UserController::delete
