#index:
#    path: /
#    controller: App\Controller\DefaultController::index
register:
  path: /registeruser
  controller: App\Controller\UserRegistrationController::register

profile:
  path: /profile
  controller: App\Controller\UserController::profile

login:
  #delegate login to security controller https://symfony.com/doc/current/security/form_login_setup.html
  path: /login
  #controller: App\Controller\UserController::login
  controller: App\Controller\SecurityController::login

logout:
  path: /logout
  controller: App\Controller\UserController::logout

user_delete:
  path: /user/delete
  controller: App\Controller\UserController::delete

authors:
#  some magic for security and prevention too long lists, see http://symfony.com/doc/current/routing.html#giving-placeholders-a-default-value
  path: /authors/{page}
  controller: App\Controller\AuthorController::index
  methods:    [GET, HEAD]
  defaults:
    page: 1
  requirements:
    page: '\d+'

#  %TODO nested & parametrized route's names, is it possible ?

author_new:
  path: /author/new
  controller: App\Controller\AuthorController::new

author_show:
  path: /author/show/{id<\d+>}
  controller: App\Controller\AuthorController::show
  methods:    [GET, HEAD]

author_edit:
  path: /author/edit/{id<\d+>}
  controller: App\Controller\AuthorController::edit

author_delete:
  path: /author/delete/{id<\d+>}
  controller: App\Controller\AuthorController::delete
  methods:    [DELETE]